/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Image.ImageProcessor;
import Image.Image_002;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;

/**
 *
 * @author power
 */
public class GeneralImageControls extends AbstractControlPanel {

    /**
     * Creates new form GeneralImageControls
     */
    public GeneralImageControls() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFaceRectangle = new javax.swing.JButton();

        setFaceRectangle.setText("setFaceRectangle");
        setFaceRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFaceRectangleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setFaceRectangle)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setFaceRectangle)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setFaceRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFaceRectangleActionPerformed
        Image_002 processed = parent.ActiveImage;
        processed.setRectangle(parent.picturePanel.getRectangle());
        //parent.picturePanel.DrawImage(parent.ActiveImage.getImage());
    }//GEN-LAST:event_setFaceRectangleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton setFaceRectangle;
    // End of variables declaration//GEN-END:variables
}
