/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Image.ImageProcessor;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.awt.image.WritableRaster;

/**
 *
 * @author power
 */
public class pixelAnalysis extends AbstractControlPanel {

    /**
     * Creates new form pixelAnalysis
     */
    public pixelAnalysis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RGB = new javax.swing.JButton();
        rgb = new javax.swing.JButton();
        YCbCr = new javax.swing.JButton();
        HSB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Median = new javax.swing.JButton();

        RGB.setText("RGB");
        RGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGBActionPerformed(evt);
            }
        });

        rgb.setText("rgb");
        rgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbActionPerformed(evt);
            }
        });

        YCbCr.setText("YCbCr");
        YCbCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YCbCrActionPerformed(evt);
            }
        });

        HSB.setText("HSB");
        HSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSBActionPerformed(evt);
            }
        });

        jButton1.setText("Mean");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Median.setText("Median");
        Median.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Median)
                    .addComponent(jButton1)
                    .addComponent(HSB)
                    .addComponent(YCbCr)
                    .addComponent(rgb)
                    .addComponent(RGB))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(RGB)
                .addGap(18, 18, 18)
                .addComponent(rgb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YCbCr)
                .addGap(18, 18, 18)
                .addComponent(HSB)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(Median)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGBActionPerformed
        Shape s=parent.picturePanel.s;
        int xi=s.x;
        int yi=s.y;
        if(xi>0 && yi>0){
            BufferedImage i=parent.picturePanel.lastDrawnImage;
            WritableRaster wr=i.getRaster();
            int []a=null;
            a=wr.getPixel(xi, yi, a);
            System.out.println("R="+a[0]+" G="+a[1]+" B="+a[2]);
        }
    }//GEN-LAST:event_RGBActionPerformed

    private void rgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgbActionPerformed
        Shape s=parent.picturePanel.s;
        int xi=s.x;
        int yi=s.y;
        if(xi>0 && yi>0){
            BufferedImage i=parent.picturePanel.lastDrawnImage;
            WritableRaster wr=i.getRaster();
            int []a=null;
            float []b=null;
            a=wr.getPixel(xi, yi, a);
            b=ImageProcessor.getPixelRatio(a);
            System.out.println("r="+b[0]+"g="+b[1]+"b="+b[2]);
        }
    }//GEN-LAST:event_rgbActionPerformed

    private void YCbCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YCbCrActionPerformed
        Shape s=parent.picturePanel.s;
        int xi=s.x;
        int yi=s.y;
        if(xi>0 && yi>0){
            BufferedImage i=parent.picturePanel.lastDrawnImage;
            WritableRaster wr=i.getRaster();
            int []a=null;
            a=wr.getPixel(xi, yi, a);int R=a[0],G=a[1], B=a[2];
            int y = (int)( 0.299   * R + 0.587   * G + 0.114   * B);
            int Cb = (int)(-0.16874 * R - 0.33126 * G + 0.50000 *B);
            int Cr = (int)( 0.50000 * R - 0.41869 * G- 0.08131 * B);
            System.out.println("y="+y+" cb="+Cb+" cr="+Cr);
        }
    }//GEN-LAST:event_YCbCrActionPerformed

    private void HSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BufferedImage img=parent.picturePanel.lastDrawnImage;
        Rectangle r=parent.sourceImage.rectangle;
        parent.picturePanel.DrawImage(Image.HistogramEQ.replaceMeanWithWhite(parent.sourceImage.originalImage.getSubimage(r.x, r.y, r.width, r.height), 0));
        //parent.picturePanel.DrawImage(parent.sourceImage.getFaceImage());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedianActionPerformed
        BufferedImage img=parent.picturePanel.lastDrawnImage;
        Rectangle r=parent.sourceImage.rectangle;
        parent.picturePanel.DrawImage(Image.HistogramEQ.replaceMeanWithWhite(parent.sourceImage.originalImage.getSubimage(r.x, r.y, r.width, r.height), 0));
    }//GEN-LAST:event_MedianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HSB;
    private javax.swing.JButton Median;
    private javax.swing.JButton RGB;
    private javax.swing.JButton YCbCr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton rgb;
    // End of variables declaration//GEN-END:variables
}
